# Generated by Django 3.0.6 on 2022-02-01 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='Username')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groups_users.UserGroups')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
