# Generated by Django 3.0.6 on 2022-02-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Data Analytics', 'Data Analytics'), ('Services Analytics', 'Services Analytics'), ('Voice Analytics', 'Voice Analytics'), ('Queue Stats', 'Queue Stats'), ('Voice Stats', 'Voice Stats'), ('Video', 'Video'), ('Smart Access', 'Smart Access'), ('Diagrams', 'Diagrams')], default='Video', max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
    ]
